Run generate from hpw.js and additional modularity
HowProgrammingWorks/Labs pull request #6
Opened 2017-10-09 23:16 UTC by Kowalski0805

Added few commands to hpw.js:
- "hpw generate" creates text file (.txt by default) with tasks
- "hpw help" list all available commands

Splitted generate.js into 4 modules: 1 for generating tasks array and 3 other for each file format (txt, csv, json)

2017-10-09 23:29 UTC, tshemsedinov requested changes
A few fixes needed

2017-10-09 23:29 UTC, tshemsedinov commented on lib/generate.js
> +const supportedFileTypes = {
Может хватит просто массива `['json', 'txt', 'csv']` ?

2017-10-09 23:30 UTC, tshemsedinov commented on lib/generate.js
> +module.exports = function(personId, ...params) {
Лучше объявляем отдельно функцию (и как лямбду) и потом ее присваиваем в module.exports и через {} лучше

2017-10-09 23:31 UTC, revan730 commented
Add start script to package.json

2017-10-10 00:46 UTC, tshemsedinov approved these changes

2017-10-10 00:48 UTC, merged